"""Add loyalty_status to customers table

Revision ID: 94a18a60fd3d
Revises: 001
Create Date: 2025-10-23 04:11:00.478008+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a18a60fd3d'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('loyalty_status', sa.String(length=50), nullable=False, server_default='bronze'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'loyalty_status')
    # ### end Alembic commands ###